### ISSUE TITLE
Change key-value pair separator in meta element

### ISSUE THREAD

**Issue by wimlawrence** [jfc3/atehere#643]
Replace the semicolon with a comma in the Viewport META element
https://github.com/jfc3/atehere/blob/2488415af80f2284faa9e2a7c6c8dff8a15b5c33/index.php#L20

**Comment by jfc3** [comment]
Thanks, for pointing that out. Not sure where I copied and pasted that from but will look at other code of mine which probably has the same issue.

Luckily, it works even though I'm using a semicolon instead of a comma.

**Comment by jfc3** [comment]
@wimlawrence ,

Changed key-value pair separator in meta element from semicolon to a comma along with changing initial scale from 1.0 to 1 for both INDEX.php and TEST.php pages.

Moved pages to server.

**Comment by jfc3** [comment]
Need to update ReadMe file with the update.

**Comment by jfc3** [comment]
Updated ReadMe about the changes done for this issue.
